import fs from 'node:fs/promises';
import {messages} from './src/i18n.js';import {body} from './src/template.js';
const origin=process.env.SITE_URL||'https://imageto-pdf-eta.vercel.app';
await fs.rm('dist',{recursive:true,force:true});await fs.mkdir('dist/vendor',{recursive:true});await fs.cp('src','dist/src',{recursive:true});
for(const [from,to]of [['node_modules/pdf-lib/dist/pdf-lib.min.js','pdf-lib.min.js'],['node_modules/pdfjs-dist/build/pdf.mjs','pdf.mjs'],['node_modules/pdfjs-dist/build/pdf.worker.mjs','pdf.worker.mjs'],['node_modules/pdfjs-dist/cmaps','cmaps'],['node_modules/pdfjs-dist/standard_fonts','standard_fonts']])await fs.cp(from,'dist/vendor/'+to,{recursive:true});
await fs.cp('public','dist',{recursive:true});
for(const lang of ['en','ko']){const t=messages[lang];await fs.mkdir(`dist/${lang}`,{recursive:true});const html=`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${t.title}</title><meta name="description" content="${t.description}"><meta name="theme-color" content="#edf5f8"><meta name="robots" content="index,follow"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="canonical" href="${origin}/${lang}/"><link rel="alternate" hreflang="ko" href="${origin}/ko/"><link rel="alternate" hreflang="en" href="${origin}/en/"><link rel="alternate" hreflang="x-default" href="${origin}/"><meta property="og:type" content="website"><meta property="og:title" content="${t.title}"><meta property="og:description" content="${t.description}"><meta property="og:url" content="${origin}/${lang}/"><meta property="og:locale" content="${lang==='ko'?'ko_KR':'en_US'}"><link rel="stylesheet" href="/src/style.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebApplication',name:'Image to PDF',url:`${origin}/${lang}/`,description:t.description,applicationCategory:'UtilitiesApplication',operatingSystem:'Any',inLanguage:lang,offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}})}</script><script defer src="/vendor/pdf-lib.min.js"></script><script type="module" src="/src/app.js"></script><script>window.va=window.va||function(){(window.vaq=window.vaq||[]).push(arguments)}</script><script defer src="/_vercel/insights/script.js"></script></head><body>${body(t,lang)}</body></html>`;await fs.writeFile(`dist/${lang}/index.html`,html);}
await fs.writeFile('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
await fs.writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">${['en','ko'].map(lang=>`<url><loc>${origin}/${lang}/</loc><xhtml:link rel="alternate" hreflang="en" href="${origin}/en/"/><xhtml:link rel="alternate" hreflang="ko" href="${origin}/ko/"/><xhtml:link rel="alternate" hreflang="x-default" href="${origin}/"/></url>`).join('')}</urlset>`);
console.log('Built Korean and English pages.');
