export const icons={upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 16v4a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-4"/>',rotate:'<path d="M20 10a8 8 0 1 0-1 7M20 4v6h-6"/>',delete:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/>',up:'<path d="m6 14 6-6 6 6"/>',down:'<path d="m6 10 6 6 6-6"/>',left:'<path d="m14 6-6 6 6 6"/>',right:'<path d="m10 6 6 6-6 6"/>',download:'<path d="M12 3v13m-5-5 5 5 5-5M4 17v4h16v-4"/>',share:'<path d="M12 16V3m-5 5 5-5 5 5M5 12v9h14v-9"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',zoom:'<circle cx="10" cy="10" r="7"/><path d="m15 15 6 6M7 10h6m-3-3v6"/>',file:'<path d="M14 2H5v20h14V7zM14 2v5h5M8 12h8m-8 4h5"/>',grip:'<path d="M9 5h.01M15 5h.01M9 12h.01M15 12h.01M9 19h.01M15 19h.01"/>'};
export const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||icons.file}</svg>`;
export function body(t,lang){const x=(k)=>`data-i18n="${k}"`;return `
<header class="header"><a class="brand" href="/${lang}/"><span class="brand-icon">${icon('file')}</span><span>Image <small>to</small> PDF</span></a><nav class="language" aria-label="Language"><a href="/ko/" data-lang="ko" lang="ko" ${lang==='ko'?'aria-current="true"':''}>한국어</a><a href="/en/" data-lang="en" lang="en" ${lang==='en'?'aria-current="true"':''}>EN</a></nav></header>
<main><div class="intro"><p class="eyebrow" ${x('eyebrow')}>${t.eyebrow}</p><h1 ${x('heading')}>${t.heading}</h1><p ${x('intro')}>${t.intro}</p></div>
<div class="workspace"><div class="editor"><section class="card files"><div class="section-title"><h2><span class="step coral">01</span><span ${x('files')}>${t.files}</span><span id="file-count" class="badge">0</span></h2><button class="text-button" id="clear" hidden ${x('clear')}>${t.clear}</button></div>
<input id="file-input" type="file" accept="image/jpeg,image/png,image/webp,application/pdf,.jpg,.jpeg,.png,.webp,.pdf" multiple hidden>
<button id="drop-zone" class="drop-zone"><span class="upload-icon">${icon('upload')}</span><strong ${x('add')}>${t.add}</strong><span ${x('drop')}>${t.drop}</span><small ${x('formats')}>${t.formats}</small></button>
<div id="file-list" class="file-list"></div><p class="private-note">${icon('lock')}<span ${x('local')}>${t.local}</span></p></section>
<section class="card settings"><div class="section-title"><h2><span class="step mint">02</span><span ${x('arrange')}>${t.arrange}</span></h2></div><fieldset id="settings"><legend class="sr-only" ${x('arrange')}>${t.arrange}</legend><label class="field-label" ${x('layout')}>${t.layout}</label><div class="layouts" role="group" aria-label="${t.layout}">${[1,2,4].map((n,i)=>`<button class="layout-choice ${n===2?'selected':''}" data-count="${n}" aria-pressed="${n===2}"><span class="layout-symbol slots-${n}">${Array(n).fill('<i></i>').join('')}</span><b>${n}</b><small ${x(['one','two','four'][i])}>${t[['one','two','four'][i]]}</small></button>`).join('')}</div>
<div class="two-fields"><label><span ${x('paper')}>${t.paper}</span><select id="paper"><option value="a4">A4 · 210 × 297 mm</option><option value="letter">Letter · 8.5 × 11 in</option></select></label><label><span ${x('orientation')}>${t.orientation}</span><select id="orientation"><option value="portrait" ${x('portrait')}>${t.portrait}</option><option value="landscape" selected ${x('landscape')}>${t.landscape}</option></select></label></div>
<label class="range-label"><span ${x('margin')}>${t.margin}</span><output id="margin-value">5 mm</output><input id="margin" type="range" min="0" max="25" value="5" step="0.5"></label>
<details><summary ${x('advanced')}>${t.advanced}</summary><label class="range-label"><span ${x('gap')}>${t.gap}</span><output id="gap-value">4 mm</output><input id="gap" type="range" min="0" max="20" value="4" step="0.5"></label><div class="two-fields"><label><span ${x('copies')}>${t.copies}</span><input id="copies" type="number" min="1" max="20" step="1" value="1" inputmode="numeric"></label><label><span ${x('repeat')}>${t.repeat}</span><select id="repeat"><option value="each" ${x('each')}>${t.each}</option><option value="set" ${x('set')}>${t.set}</option></select></label></div><label class="full-field"><span ${x('fit')}>${t.fit}</span><select id="fit"><option value="contain" ${x('contain')}>${t.contain}</option><option value="cover" ${x('cover')}>${t.cover}</option></select></label><p class="hint" id="crop-hint" hidden ${x('cropHint')}>${t.cropHint}</p><label class="check"><input type="checkbox" id="fillLast"><span ${x('fillLast')}>${t.fillLast}</span></label><label class="check"><input type="checkbox" id="cut"><span ${x('cut')}>${t.cut}</span></label></details></fieldset></section></div>
<aside class="preview-column"><section class="card preview-card"><div class="section-title"><h2><span class="step lilac">03</span><span ${x('preview')}>${t.preview}</span></h2><button class="icon-button" id="zoom" title="${t.zoom}" aria-label="${t.zoom}" disabled>${icon('zoom')}</button></div><div class="preview-stage"><div id="preview-empty"><span class="empty-icon">${icon('file')}</span><strong ${x('previewEmpty')}>${t.previewEmpty}</strong><p ${x('previewHint')}>${t.previewHint}</p></div><canvas id="preview-canvas" hidden></canvas></div><div class="page-navigation"><button id="prev" class="icon-button" aria-label="${t.prev}" disabled>${icon('left')}</button><span id="page-status">—</span><button id="next" class="icon-button" aria-label="${t.next}" disabled>${icon('right')}</button></div><p class="hint" ${x('printHint')}>${t.printHint}</p></section><section class="card export-card"><label><span ${x('fileName')}>${t.fileName}</span><div class="filename"><input id="filename" value="coloring-pages" maxlength="100"><span>.pdf</span></div></label><div class="export-actions"><button class="primary" id="save" disabled>${icon('download')}<span ${x('save')}>${t.save}</span></button><button class="secondary" id="share" disabled>${icon('share')}<span ${x('prepare')}>${t.prepare}</span></button></div><p id="export-status" role="status"></p></section></aside></div>
<section class="guide"><h2 ${x('guideTitle')}>${t.guideTitle}</h2><p ${x('guideIntro')}>${t.guideIntro}</p><div class="guide-steps">${[1,2,3].map(n=>`<article><h3 ${x('step'+n)}>${t['step'+n]}</h3><p ${x('step'+n+'p')}>${t['step'+n+'p']}</p></article>`).join('')}</div><h2 ${x('faq')}>${t.faq}</h2>${[1,2,3,4].map(n=>`<details><summary ${x('q'+n)}>${t['q'+n]}</summary><p ${x('a'+n)}>${t['a'+n]}</p></details>`).join('')}</section></main><footer><span>Image to PDF</span><p ${x('footer')}>${t.footer}</p><small ${x('privacy')}>${t.privacy}</small></footer><div id="notification" role="status" hidden></div><dialog id="zoom-dialog"><button id="close-zoom" class="secondary" ${x('close')}>${t.close}</button><div><img id="zoom-image" alt="${t.preview}"></div></dialog><dialog id="clear-dialog"><p ${x('confirm')}>${t.confirm}</p><div class="dialog-actions"><button id="cancel-clear" class="secondary" ${x('cancel')}>${t.cancel}</button><button id="confirm-clear" class="primary" ${x('clear')}>${t.clear}</button></div></dialog><div id="busy" hidden><div><span class="spinner"></span><p id="busy-text" role="status"></p><progress id="progress" max="100" value="0"></progress></div></div><noscript>${t.noscript}</noscript>`;}
